### ISSUE TITLE
Raw arrays in output file

### ISSUE THREAD

**Issue by SchetininVitaliy** [linev/go4#1]
Hi go4 developers,

Is there good approach to write raw arrays in output store?

In my case it is not convenient to have TGo4EventElement in result root files.

**Comment by linev** [comment]
Hi Vitaly,

Theoretically it should be possible, but we never provide examples and GUI control elements for that.
Normally one stores output event data into the ROOT TTree and then uses simple ROOT macros convert such data to something else. Is such solution ok for you?

Regards,
Sergey

**Comment by SchetininVitaliy** [comment]
Hi Sergey,

Unfortunately not.
The initial task that we faced was to organize a dynamically formed structure of the event. We have xml file with setup and electronics description. And base on fields in this file organize structure of event.

For this purpose we started to use TGo4Composite event. But faced the problem with extremely huge IO. Because TGoComposite event write metadata(event description) for each entry.

Current idea is to add TGo4Step which will save the date as tree with raw arrays. Structure of tree will be created by xml. So, we will have light files with data and separate xml with metadata.

This is origin of my question) I just want to create branch in output file dynamically in TGo4Step and write data there. Sure,  I can create separate file in my TGo4Step, but decided to ask is there some way which framework suggested.

**Comment by linev** [comment]
I see. Then I need to add some functionality in core framework that 
arbitrary `TGo4EventStore`-derived class can be configured and created in the user analysis. 
And then I will provide simple example for that.
This will take some time - let say one week.

**Comment by SchetininVitaliy** [comment]
I really appreciate it!

**Comment by linev** [comment]
I prepared [Go4UserStore](https://github.com/linev/go4/tree/master/Go4ExampleUserStore) example.
It also should be possible to configure it via the GUI. 
When running from command line:
```
go4analysis -random -userstore file.root -number 10000
```
If necessary, one can extend `TGo4UserStoreParameter` class and add few more fields like in `TGo4FileStoreParameter`

**Comment by SchetininVitaliy** [comment]
This is exactly what I need! Thanks!

**Comment by SchetininVitaliy** [comment]
BTW, how does release cycle work in go4? Will code from this repo be used to create releases for https://www.gsi.de/en/work/research/experiment_electronics/data_processing/data_analysis/the_go4_home_page.htm

**Comment by linev** [comment]
This repository just copy from https://subversion.gsi.de/go4/trunk/
I plan go4 release after ROOT 6.24 while then some go4 components can be simplified

**Comment by SchetininVitaliy** [comment]
As I understood, here https://github.com/linev/go4/blob/master/Go4ExampleUserStore/TXXXAnalysis.cxx#L58 we need to use TGo4UserStoreParameter. Because you have this condition https://github.com/linev/go4/blob/master/Go4EventServer/TGo4StepFactory.cxx#L182.

Somehow example works)  But I can not reproduce it int my code.

**Comment by linev** [comment]
Starting point is this:
https://github.com/linev/go4/blob/master/Go4ExampleUserStore/TXXXAnalysis.cxx#L51
It defines store class.

Of course, you can set TGo4UserStoreParameter by default - I will adjust example later

**Comment by linev** [comment]
I update example and readme.
Also in example store will be enabled by default.
