### ISSUE TITLE
Trouble finding system-wide installation of ROOT

### ISSUE THREAD

**Issue by eamjensen** [linev/go4#2]
Hello!

Long-time user, first-time writer!

On Go4 version version 6.2.0 (retrieved from the gsi.de website), the CMake-generated file *Go4Config.cmake* does not accommodate users with system-wide installations of ROOT in the "reuse ROOT configurations" section.

My suggestion is to add a `find_package(ROOT [QUIET])` call at the head of this section in the corresponding *Go4Config.cmake.in* file and then make a check on whether ROOT was found or not. If it was, there is no need to include the *ROOTConfig.cmake* file (this is what `find_package()` does), and if it wasn't then one can proceed with the current CMake specifications.

Cheers,
Erik

**Comment by linev** [comment]
Hi Erik,

Grate to see here first issue!

I guess, you speak about building of analysis code?
Can you check that  PR #3 helps to solve your problem.
If not - can you propose PR?

Regards,
Sergey

**Comment by eamjensen** [comment]
Hi Sergey,

Thanks. This was part of the solution.
I have gone a bit further with some modifications to the CMake specifications in my pull request #4.

I hope this can be useful to you.

Kind regards from
Erik

**Comment by eamjensen** [comment]
This was fixed by a mixture of PR #3 and PR #5. Closing issue.
